### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by kawindme** [virocon-organization/viroconcom#12]
See https://coveralls.io/github/ahaselsteiner/viroconcom?branch=master for test coverage. The targeted coverage is 95% for each file.
Reached target coverage for:
- [x] _n_sphere.py
- [ ] contours.py
- [ ] distributions.py
- [ ] fitting.py
- [x] params.py

**Comment by kawindme** [comment]
as described in ahaselsteiner/virocon#72 doctests should be run automatically

**Comment by ahaselsteiner** [comment]
Test coverage reached 90%. We now focus on virocon v2 where tests are rewritten such that I close this issue, which was about virocon v1.
